### PR TITLE
Switch from xdg-app-paths to env-paths

### LINKED ISSUE #778: Alchemy can't be ran with deno
When trying to run alchemy with deno users will see the following error:

```bash
deno run alchemy.run.ts
error: [ERR_MODULE_NOT_FOUND] Cannot find module 'file:///Users/just-be/Library/Caches/deno/npm/registry.npmjs.org/xdg-app-paths/8.3.0/src/mod.deno.ts' imported from 'file:///Users/just-be/Library/Caches/deno/npm/registry.npmjs.org/alchemy/0.55.3/lib/cloudflare/oauth.js'
```

This is actually an issue with an upstream dependency which I've created an issue for here: https://github.com/rivy/js.xdg-app-paths/issues/1

There was a conversation back in 2021 that the author of the package was in around how to package for deno: https://github.com/denoland/deno/issues/3196#issuecomment-782789368. While well-intentioned, Deno just consumes node-like packages and it would've been better had they not tried to do something special for deno. 

I'm going to follow up with a PR to swap over to `env-paths`.

### PR DESCRIPTION
**Pull request by just-be-dev**
Fixes #778 

`xdg-app-paths` tries to do special handling for deno projects, but it did so before Deno 2.0 release. That special handling is broken now and causes alchemy to fail for anyone trying to run it in Deno. I've instead switched over to `env-paths` which hasn't been updated as recently but has significantly more downloads. It's a sindresorhus package.

### CODE REVIEW

File: alchemy/src/cloudflare/oauth.ts [hunk 1]
```diff
@@ -70,7 +70,7 @@ export const getRefreshedWranglerConfig = singleFlight(() =>
 );
 
 const getWranglerConfigPath = memoize(async () => {
-  const xdgConfigDir = xdgAppPaths(".wrangler").config();
+  const xdgConfigDir = envPaths("wrangler", { suffix: "" }).config;
```
Comment (just-be-dev) [inline alchemy/src/cloudflare/oauth.ts]: The `suffix` option is important here because otherwise `envPaths` will append a `-nodejs` suffix onto the config path. The original intent of this package is for storing new things, not necessarily looking up existing. Still, we can get the same behavior by passing in an empty string.

**Comment by sam-goodwin** [comment]
@john-royal  any thoughts on this one?

**Comment by john-royal** [comment]
Honestly, I've been wanting to switch to this because it's better architected (like a good sindresorhus package) and more popular than `xdg-app-paths`.

We should be aware that this may break compatibility with `wrangler login` in some edge cases.

For context, XDG paths are really only a Linux thing, so for other platforms, you use an analog like `AppData/Roaming` on Windows or `Library/Preferences` on Mac. These directories are fairly standardized, but there are rare edge cases where one library might have a different opinion from another. The reason we use `xdg-app-paths` right now isn't because it's the best option, but because we had a user hit an edge case a few weeks ago, so I figured it's best to keep our behavior fully compatible.

However, given that we have our own `alchemy login` command and we're moving away from relying on Wrangler auth anyway, I say merge it. Most users will be unaffected; the few that are can simply run `alchemy login` and they'll be taken care of.

File: alchemy/src/cloudflare/oauth.ts (hunk 1 above)
Comment (just-be-dev) [reply alchemy/src/cloudflare/oauth.ts]:
```suggestion
  const xdgConfigDir = envPaths(".wrangler", { suffix: "" }).config;
```
