### PR TITLE
fix(cloudflare): skip path validation during astro output type check

### LINKED ISSUE #860: Unable to resolve alchemy server type if using the alchemy astro vite adapter
When running `alchemy deploy` we are unable to infer to correct output type for the cloudflare astro resource.

This is the function we use to infer the astro output type.

```ts
async function resolveOutputType(cwd: string): Promise<"server" | "static"> {
  const candidates = [
    "astro.config.mjs",
    "astro.config.js",
    "astro.config.ts",
    "astro.config.mts",
  ];
  for (const candidate of candidates) {
    try {
      const config = await import(join(cwd, candidate));
      if (
        typeof config.default === "object" &&
        config.default &&
        "output" in config.default &&
        typeof config.default.output === "string"
      ) {
        return config.default.output;
      }
      return "static";
    } catch {
      // ignore
    }
  }
  return "static";
}

```

The problem is when we try and import an astro config that references the alchemy vite adapter it will error with
```
41 |
42 | const warned = new Set<string>();
43 |
44 | const warnOrThrow = (message: string, throws: boolean) => {
45 |   if (throws) {
46 |     throw new Error(message);
               ^
error: The Wrangler config path, ".alchemy/local/wrangler.jsonc", could not be found. Please run `alchemy dev` or `alchemy deploy` to create it.
      at warnOrThrow (D:\code\OSS\alchemy\alchemy\alchemy\src\cloudflare\miniflare\paths.ts:46:11)
      at validateConfigPath (D:\code\OSS\alchemy\alchemy\alchemy\src\cloudflare\miniflare\paths.ts:11:5)
      at getPlatformProxyOptions (D:\code\OSS\alchemy\alchemy\alchemy\src\cloudflare\cloudflare-env-proxy.ts:42:17)
      at alchemy (D:\code\OSS\alchemy\alchemy\alchemy\src\cloudflare\astro\plugin.ts:6:20)
      at D:\worktemp\alchemy\astro-mono-test\deployments\astro\astro.config.mjs:8:11
      at requestImportModule (2:1)
```

alchemy dev works fine.

### PR DESCRIPTION
**Pull request by john-royal**
Closes #860.

Uses `AsyncLocalStorage` to detect when Miniflare path validation calls should not cause an error to be thrown.

### CODE REVIEW

File: alchemy/src/cloudflare/miniflare/paths.ts [hunk 1]
```diff
@@ -1,5 +1,15 @@
+import { AsyncLocalStorage } from "node:async_hooks";
 import { existsSync, readlinkSync, statSync } from "node:fs";
 
+const dynamicImportContext = new AsyncLocalStorage<boolean>();
```
Comment (sam-goodwin) [inline alchemy/src/cloudflare/miniflare/paths.ts:4]: is async local storage necessary? what was the justification?

**Comment by Mkassabov** [comment]
can confirm this does fix my issue on #860

File: alchemy/src/cloudflare/miniflare/paths.ts (hunk 1 above)
Comment (john-royal) [reply alchemy/src/cloudflare/miniflare/paths.ts:4]: I was split between 3 ways of doing this:
1. environment variable
2. `globalThis`
3. async local storage

Figured #3 was the least leaky - no additional global, keeps it isolated.

Happy to change it if you want

Comment (Mkassabov) [reply alchemy/src/cloudflare/miniflare/paths.ts:4]: isn't asl more leaky? I'd expect this to break if I ran two astro resources at the same time (e.g. with `promise.all([astro1, astro2])`)

Comment (john-royal) [reply alchemy/src/cloudflare/miniflare/paths.ts:4]: Why would that break?

We're using `.run()` instead of `.enter()` so it's scoped to the Astro dynamic import. Running multiple in parallel shouldn't be an issue.
