### PR TITLE
fix: handle dangling processes

### LINKED ISSUE #747: Dangling processes
```
Port 5189 is in use, trying another one...
Port 5190 is in use, trying another one...
Port 5191 is in use, trying another one...
Port 5192 is in use, trying another one...
Port 5193 is in use, trying another one...
Port 5194 is in use, trying another one...
Port 5195 is in use, trying another one...
Port 5196 is in use, trying another one...
```

### PR DESCRIPTION
**Pull request by john-royal**
Closes #747:
- Added `this.spawn()` to `Scope` and `Context` to register a process with a teardown hook
- Refactored Miniflare controller
- Use `signal-exit` to add exit listener (same as Miniflare)

We don't intercept the Miniflare exit anymore since that was causing issues. However, this does mean when you exit with ctrl + C, you get a 130 exit code instead of 0.

I did try implementing the IPC solution ([branch](https://github.com/sam-goodwin/alchemy/tree/john/747-dangling-process-ipc)). It works on its own, but not with our CLI, so I didn't include it in this PR.

### CODE REVIEW

File: alchemy/src/scope.ts [hunk 1]
```diff
@@ -466,6 +477,8 @@ export class Scope {
     });
 
     if (!this.parent && process.env.ALCHEMY_TEST_KILL_ON_FINALIZE) {
+      this.logger.log("[debug] Killing on finalize");
+      await Promise.allSettled(this.cleanups.map((cleanup) => cleanup()));
```
Comment (sam-goodwin) [inline alchemy/src/scope.ts]: Should we provide a function that does this since it's done in multiple places?

`cleanup()`

File: alchemy/src/scope.ts [hunk 2]
```diff
@@ -537,6 +550,49 @@ export class Scope {
...
+      return true;
+    });
+  }
+
+  /**
+   * Register a cleanup function that will be called when the scope is finalized.
+   * The provided function should create resources and return an object with a cleanup function.
+   * This should only be called on the root scope to ensure proper cleanup.
+   */
+  public async spawn<T extends { cleanup: () => Promise<void> }>(
```
Comment (sam-goodwin) [inline alchemy/src/scope.ts]: That's not what this function does

File: alchemy/src/scope.ts [hunk 3]
```diff
@@ -466,6 +477,8 @@ export class Scope {
     });
 
     if (!this.parent && process.env.ALCHEMY_TEST_KILL_ON_FINALIZE) {
```
Comment (sam-goodwin) [inline alchemy/src/scope.ts:472]: This only runs during our tests? Of are you also catching a signal and running it?

File: alchemy/src/scope.ts [hunk 4]
```diff
@@ -178,6 +183,12 @@ export class Scope {
     }
     this.phase = phase;
 
+    // Install exit handlers on first root scope creation
+    if (!this.parent && !Scope.exitHandlerInstalled) {
+      Scope.exitHandlerInstalled = true;
+      this.installExitHandlers();
+    }
```
Comment (sam-goodwin) [inline alchemy/src/scope.ts]: Maybe do it in alchemy where the root is created instead of in he scope?

File: alchemy/src/scope.ts (hunk 3 above)
Comment (john-royal) [reply alchemy/src/scope.ts:472]: Yeah this only runs during tests. For some reason tests would fail without this

File: alchemy/src/scope.ts (hunk 2 above)
Comment (john-royal) [reply alchemy/src/scope.ts]: Agree. Any idea for what we should call it instead?

We need a function that can return a cleanup for use with Miniflare and the worker tail.

File: alchemy/src/scope.ts (hunk 1 above)
Comment (john-royal) [reply alchemy/src/scope.ts]: Sure

File: alchemy/src/scope.ts (hunk 2 above)
Comment (sam-goodwin) [reply alchemy/src/scope.ts]: It seems overly complicated. Why not just onCleanup?

It's also not clear why the user provides a function that we immediately call

Comment (john-royal) [reply alchemy/src/scope.ts]: Fair enough

File: alchemy/src/cloudflare/miniflare/build-worker-options.ts
Comment (sam-goodwin) [inline alchemy/src/cloudflare/miniflare/build-worker-options.ts:1]: what changed in this file? Moving files around can make it harder to review code

File: alchemy/src/cloudflare/miniflare/controller.ts
Comment (sam-goodwin) [inline alchemy/src/cloudflare/miniflare/controller.ts:1]: we should make up our mind on naming conventions for the file, should this be miniflare-controller.ts? 

i see miniflare-worker-proxy.ts, but `miniflare-worker-options.ts` was just renamed to `build-worker-options.ts`

File: alchemy/src/scope.ts [hunk 5]
```diff
@@ -537,6 +550,49 @@ export class Scope {
...
+   * Install global process exit handlers to ensure cleanup
+   */
+  private installExitHandlers() {
+    if (this.parent) return;
+    onExit((code) => {
+      if (this.cleanups.length === 0) return;
+      this.logger.log(kleur.gray("Exiting..."));
+      Promise.allSettled(this.cleanups.map((cleanup) => cleanup())).then(() => {
+        console.log("Exiting with code:", code); // this never gets logged, thanks Miniflare
+        process.exit(code);
```
Comment (sam-goodwin) [inline alchemy/src/scope.ts]: why do we need to call this?

File: alchemy/src/cloudflare/miniflare/controller.ts
Comment (john-royal) [reply alchemy/src/cloudflare/miniflare/controller.ts:1]: I figured it doesn't need the prefix if it's already in the `miniflare` directory, is that ok with you or would you prefer to keep the prefix?

File: alchemy/src/scope.ts (hunk 5 above)
Comment (john-royal) [reply alchemy/src/scope.ts]: If you return `true` (as we do on line 565), that tells the `onExit` function that we'll call process.exit, so don't exit for us. This is important because otherwise, it'll exit before those cleanup promises can be awaited (`onExit` doesn't let you return a promise).

The debug log I added there isn't 100% true - it doesn't get logged if Miniflare is there intercepting the exit signal (which it shouldn't, I can make an issue for that tomorrow), but if we don't have Miniflare messing up our process (e.g. if your app is just a Vite website or something), then we do want to handle the exit ourselves.

File: alchemy/src/cloudflare/miniflare/build-worker-options.ts
Comment (john-royal) [reply alchemy/src/cloudflare/miniflare/build-worker-options.ts:1]: Before, the worker options were being assembled in multiple places:
1. The `Worker` resource would handle watching and piping the bundle output to Miniflare
2. There were multiple layers of back and forth between `miniflare-worker-options.ts`, `remote-binding-proxy.ts`, and `MiniflareServer` (`miniflare.ts`) to assemble bindings, provision the remote proxy if necessary, and finally push that updated code into Miniflare
3. This would be repeated every time the bundle updates, even when everything except the modules is the same

Now the options-wrangling is in one place, `buildWorkerOptions`, so it's easier to reason about. The function takes your bundle source and other config, the bindings are assembled once (instead of with every bundle update), and it returns an async iterator that we use to update the Miniflare instance when there's a change.

Figured this would be good to reduce indirection.

Comment (sam-goodwin) [reply alchemy/src/cloudflare/miniflare/build-worker-options.ts:1]: Makes sense.

File: alchemy/src/cloudflare/miniflare/controller.ts
Comment (sam-goodwin) [reply alchemy/src/cloudflare/miniflare/controller.ts:1]: I typically try to match the exported name and the file. 

```ts
export const MiniflareController
```

This would be `miniflare-controller.ts`

**Comment by john-royal** [comment]
Just updated it to address your feedback and tests are all passing. Should be good to merge unless there's any other changes you want!
