### PR TITLE
fix(cloudflare): ignore .alchemy directory in astro integration

### LINKED ISSUE #1293: [Astro] Error in .astro page causes reloading loop
Steps to reproduce:

- clone https://github.com/macklinu/alchemy-astro-monorepo
- run `bun i`
- run `bun dev`
- visit `http://localhost:4321/oops`

Expected: page loads _one time_ with Astro dev error overlay

Actual: page loads _in an infinite loop_ with Astro dev error overlay

This makes local development with alchemy + astro more challenging, as I need to restart my dev server every time an error occurs in a .astro page/route handler. It could also be related to the fact that I'm using bun monorepo + turbo + alchemy + astro in some way? Any ideas on what the issue might be? Thanks!

https://github.com/user-attachments/assets/cedb7189-fecc-416e-8e4d-ee06919863ce

Versions:
- alchemy 0.83.0
- bun 1.3.5
- turbo 2.7.2

### PR DESCRIPTION
**Pull request by john-royal**
Closes #1293.

Uses the same `server.watch.ignored` option as our Vite plugin. Astro lets you modify Vite settings directly but wondering if there might be something in the middle that would cause this not to work. Need to test.

May be a better solution than #1305 because it addresses the root cause: the dev server shouldn't be watching `.alchemy`. @macklinu would you mind trying out the preview package and letting me know if this fixes it?

### CODE REVIEW

File: alchemy/src/cloudflare/astro/plugin.ts [hunk 1]
```diff
@@ -7,13 +7,27 @@ const isAstroCheck =
...
+  integration.hooks["astro:config:setup"] = async (options) => {
+    options.updateConfig({
+      vite: {
+        server: {
+          watch: {
+            ignored: ["**/.alchemy/**"],
+          },
+        },
+      },
+    });
```
Comment (sam-goodwin) [inline alchemy/src/cloudflare/astro/plugin.ts:27]: Does this merge in with existing settings?

Comment (john-royal) [reply alchemy/src/cloudflare/astro/plugin.ts:27]: [Yes](https://docs.astro.build/en/reference/integrations-reference/#updateconfig-option)
