### PR TITLE
fix(cloudflare): avoid creating or deleting remote resources in local mode

### LINKED ISSUE #748: Worker URL is deleted when switching to `dev`
Image

### PR DESCRIPTION
**Pull request by john-royal**
Will close #748.

I used the "noop subresource" approach you suggested. Not sure if this is better.

### CODE REVIEW

**Comment by john-royal** [comment]
@sam-goodwin Let me know if this approach is what you were thinking.

I think it may be cleaner to have a clearer separation between local and remote resources rather than trying to handle both concurrently, but maybe I'm just doing it wrong?

Also curious if you have any ideas for the todos in worker.ts.

File: alchemy/src/cloudflare/container.ts [hunk 1]
```diff
@@ -368,6 +368,15 @@ export interface ContainerApplicationProps extends CloudflareApiOptions {
...
   adopt?: boolean;
+
+  /**
+   * If true, the container application will not be created, but will be retained if it already exists.
+   * This is used for local development.
+   *
+   * @default false
+   * @internal
+   */
+  noop?: boolean;
```
Comment (sam-goodwin) [inline alchemy/src/cloudflare/container.ts]: instead of `noop`, i was expecting `dev?: boolean` and just set it. Have the resource do nothing if `scope.dev || props.dev`

Comment (john-royal) [reply alchemy/src/cloudflare/container.ts]: Wouldn't it need to be `scope.dev && !props.dev.remote` if we were going that route?

My thinking was for this to be distinct from the usual `props.dev` since it's governed by the parent `Worker` resource — the change applies only to `ContainerApplication`, `CustomDomain`, `Route`, and `WorkerSubdomain` — the rest have the usual `props.dev`. Not sure if that makes sense though, so happy to change it.

Comment (sam-goodwin) [reply alchemy/src/cloudflare/container.ts]: They aren't exclusively sub resources. We just use them that way. 

`noop` is a strange property that only makes sense from the perspective of a sub resource. 

The outer resource should pass

```ts
dev: this.scope.dev || props.dev
```

That will ensure that it updates appropriately. And leaves the door open to us doing more with these resources in dev mode later.

Comment (john-royal) [reply alchemy/src/cloudflare/container.ts]: Got it. I do want to clarify one thing.

Context:
1. The way `Worker` is set up, we check if `this.scope.local && !props.dev.remote` — that's how we know to run in Miniflare or not
2. The `Worker` can pass `{ dev: this.scope.local && !props.dev.remote }` to the inner resource
3. But then if the inner resource becomes a no-op if `this.scope.local || props.dev`, then it won't update even if `props.dev.remote` is `true` on the parent `Worker`

Do you want us to change 1 or 2? Or would you rather change 3 to `this.scope.local && props.dev`? I don't have a strong opinion either way — let me know what you think.

Comment (sam-goodwin) [reply alchemy/src/cloudflare/container.ts]: This looks right:
```ts
{ dev: this.scope.local && !props.dev.remote }
```

File: alchemy/src/cloudflare/miniflare/build-worker-options.ts [hunk 2]
```diff
@@ -143,7 +143,7 @@ export const buildWorkerOptions = async (
             raw: true,
           });
         } else {
-          (options.d1Databases ??= {})[key] = binding.id;
+          (options.d1Databases ??= {})[key] = binding.dev.id;
```
Comment (sam-goodwin) [inline alchemy/src/cloudflare/miniflare/build-worker-options.ts:148]: this seems weird, why did it change?

Comment (john-royal) [reply alchemy/src/cloudflare/miniflare/build-worker-options.ts:148]: If you create a binding locally, this ensures the local ID for it is stable (i.e. doesn't change after you deploy it).

I did the same for KV and some of the others for that reason.

File: alchemy/src/cloudflare/bucket.ts [hunk 3]
```diff
@@ -202,88 +225,119 @@ export function isBucket(resource: Resource): resource is R2Bucket {
...
+  props: BucketProps = {},
+): Promise<R2Bucket> {
+  return await _R2Bucket(id, {
+    ...props,
+    dev: {
+      ...(props.dev ?? {}),
+      force: Scope.current.local,
+    },
+  });
+}
```
Comment (sam-goodwin) [inline alchemy/src/cloudflare/bucket.ts:239]: As we duplicate this, I wonder if we can solve it more generally.

e.g.
```ts
export interface ResourceProps {
  dev?: {
    force?: boolean;
  }
}
```

And then have `Resource` do this automatically.

Problem is I am not sure how to identify when NOT to do it. Unless we support something like:
```ts
export const MyResource = Resource("foo::bar", { local: true }, async function(..) { .. });
```

Comment (sam-goodwin) [reply alchemy/src/cloudflare/bucket.ts:239]: Let's not solve it in this PR, but think about it.

File: alchemy/src/cloudflare/bucket.ts [hunk 4]
```diff
@@ -202,88 +225,119 @@ export function isBucket(resource: Resource): resource is R2Bucket {
...
-              err instanceof CloudflareApiError &&
-              err.status === 409 &&
-              props.adopt
-            ) {
-              return await getBucket(api, bucketName, props);
-            }
-            throw err;
-          },
+    if (this.scope.local && !props.dev?.remote) {
+      return this({
```
Comment (sam-goodwin) [inline alchemy/src/cloudflare/bucket.ts:256]: Yeah, this is why I don't liek switch and never use it. Not expressive enough and awkward syntax.

File: alchemy/src/cloudflare/pipeline.ts [hunk 5]
```diff
@@ -337,6 +339,20 @@ export const Pipeline = Resource("cloudflare::Pipeline", async function <
   const api = await createCloudflareApi(props);
   const pipelineName = props.name ?? id;
 
+  if (this.scope.local && !props.dev?.remote) {
+    return this({
+      type: "pipeline",
+      id: this.output?.id ?? "",
```
Comment (sam-goodwin) [inline alchemy/src/cloudflare/pipeline.ts:345]: use the resource id?

File: alchemy/src/cloudflare/pipeline.ts [hunk 6]
```diff
@@ -337,6 +339,20 @@ export const Pipeline = Resource("cloudflare::Pipeline", async function <
...
+      name: this.output?.name ?? pipelineName,
+      endpoint: this.output?.endpoint ?? "",
+      version: this.output?.version ?? 0,
+      source: this.output?.source ?? [],
+      destination: props.destination,
+      compression: props.compression,
+      accountId: this.output?.accountId ?? "",
```
Comment (sam-goodwin) [inline alchemy/src/cloudflare/pipeline.ts:352]: Maybe use `api.accountId`?

File: alchemy/src/cloudflare/pipeline.ts [hunk 7]
```diff
@@ -337,6 +339,20 @@ export const Pipeline = Resource("cloudflare::Pipeline", async function <
   const api = await createCloudflareApi(props);
   const pipelineName = props.name ?? id;
 
+  if (this.scope.local && !props.dev?.remote) {
+    return this({
+      type: "pipeline",
+      id: this.output?.id ?? "",
+      name: this.output?.name ?? pipelineName,
+      endpoint: this.output?.endpoint ?? "",
```
Comment (sam-goodwin) [inline alchemy/src/cloudflare/pipeline.ts:347]: What does this break? Do we not have a local endpoint for a pipeline?

File: alchemy/src/cloudflare/queue-consumer.ts [hunk 8]
```diff
@@ -148,16 +157,28 @@ export const QueueConsumer = Resource(
...
   ): Promise<QueueConsumer> {
-    const api = await createCloudflareApi(props);
-
     // Get queueId from either props.queue or props.queueId
     const queueId =
       typeof props.queue === "string" ? props.queue : props.queue.id;
 
+    if (this.scope.local && props.dev) {
+      return this({
+        id: this.output?.id ?? "",
```
Comment (sam-goodwin) [inline alchemy/src/cloudflare/queue-consumer.ts:166]: resource `id`?

File: alchemy/src/cloudflare/queue-consumer.ts [hunk 9]
```diff
@@ -148,16 +157,28 @@ export const QueueConsumer = Resource(
...
+        queueId,
+        queue: props.queue,
+        type: "worker",
+        scriptName: props.scriptName,
+        settings: props.settings,
+        accountId: this.output?.accountId ?? "",
```
Comment (sam-goodwin) [inline alchemy/src/cloudflare/queue-consumer.ts:172]: These empty strings make me nervous.

File: alchemy/src/cloudflare/queue.ts [hunk 10]
```diff
@@ -208,26 +231,57 @@ export interface Queue<Body = unknown>
...
-  const api = await createCloudflareApi(props);
   const queueName = props.name ?? id;
+  const dev = {
+    id: this.output?.dev?.id ?? this.output?.id ?? id,
+    remote: props.dev?.remote ?? false,
+  };
+  if (this.scope.local && !props.dev?.remote) {
+    return this({
+      type: "queue",
+      id: this.output?.id ?? "",
```
Comment (sam-goodwin) [inline alchemy/src/cloudflare/queue.ts:260]: `?? id`?

**Review by sam-goodwin — APPROVED** [review]

File: alchemy/src/cloudflare/worker.ts [hunk 11]
```diff
@@ -522,6 +524,11 @@ export type Worker<
     placement?: {
       mode: "smart";
     };
+
+    /**
+     * Whether the worker has a remote deployment
```
Comment (sam-goodwin) [inline alchemy/src/cloudflare/worker.ts:529]: mark as @internal

Comment (sam-goodwin) [reply alchemy/src/cloudflare/worker.ts:529]: Should it be in `dev?: { hasRemote: boolean }`
