### PR TITLE
fix(cloudflare): nuxt example fails in dev

### LINKED ISSUE #738: Nuxt broken in dev mode
Image

### PR DESCRIPTION
**Pull request by john-royal**
Closes #738.

The problem was that it was importing `cloudflare:workers` when H3 requires you to access env from the `context` property.

- [x] Update example
- [x] Update template

### CODE REVIEW

**Comment by john-royal** [comment]
Update: working on type error with `index.ts`. Cloudflare's template doesn't include an `index.ts` so wonder if we can get away with just removing it.

File: examples/cloudflare-nuxt-pipeline/env.d.ts [hunk 1]
```diff
@@ -1,14 +1,15 @@
...
-  namespace Cloudflare {
-    export interface Env extends WorkerEnv {}
+declare module "h3" {
+  interface H3EventContext {
+    cf: CfProperties;
+    cloudflare: {
+      request: Request;
+      env: typeof website.Env;
+      context: ExecutionContext;
+    };
```
Comment (sam-goodwin) [inline examples/cloudflare-nuxt-pipeline/env.d.ts:12]: update alchemy/templates/nuxt

**Comment by sam-goodwin** [comment]
@claude make the similar change to the react-router template in alchemy/templates/react-router. This PR currently only updates the examples/cloudflare-react-router
